// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu.Data;

#nullable disable

namespace QuanLyChiTieu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613132052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenChiTieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChiTieu__3214EC0748AA8F80");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("NgayChi")
                        .HasDatabaseName("IX_ChiTieu_NgayChi");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("IX_ChiTieu_NguoiDungId");

                    b.HasIndex("NguoiDungId", "NgayChi")
                        .HasDatabaseName("IX_ChiTieu_NguoiDung_NgayChi");

                    b.HasIndex(new[] { "NgayChi" }, "IX_ChiTieu_NgayChi");

                    b.HasIndex(new[] { "NguoiDungId" }, "IX_ChiTieu_NguoiDungId");

                    b.ToTable("ChiTieu", null, t =>
                        {
                            t.HasTrigger("trg_CanhBaoVuotHanMuc");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 1,
                            GhiChu = "Bánh mì và cà phê",
                            NgayChi = new DateTime(2026, 4, 1, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 35000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 2,
                            GhiChu = "Di chuyển đầu tháng",
                            NgayChi = new DateTime(2026, 4, 2, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 120000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 4,
                            GhiChu = "Vé phim và nước",
                            NgayChi = new DateTime(2026, 4, 4, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 180000m,
                            TenChiTieu = "Xem phim cuối tuần"
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 5,
                            GhiChu = "Chi phí cố định tháng 4",
                            NgayChi = new DateTime(2026, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 3200000m,
                            TenChiTieu = "Tiền thuê phòng"
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 1,
                            GhiChu = "Cơm trưa",
                            NgayChi = new DateTime(2026, 4, 7, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 75000m,
                            TenChiTieu = "Ăn trưa văn phòng"
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 9,
                            GhiChu = "Làm việc buổi tối",
                            NgayChi = new DateTime(2026, 4, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 95000m,
                            TenChiTieu = "Cà phê làm việc"
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 5,
                            GhiChu = "Hóa đơn tháng 4",
                            NgayChi = new DateTime(2026, 4, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 250000m,
                            TenChiTieu = "Internet văn phòng"
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 3,
                            GhiChu = "Đồ đi làm",
                            NgayChi = new DateTime(2026, 4, 12, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 420000m,
                            TenChiTieu = "Mua áo sơ mi"
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 1,
                            GhiChu = "Quán nướng",
                            NgayChi = new DateTime(2026, 4, 14, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 210000m,
                            TenChiTieu = "Ăn tối với bạn"
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 6,
                            GhiChu = "Nhà thuốc gần nhà",
                            NgayChi = new DateTime(2026, 4, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 160000m,
                            TenChiTieu = "Thuốc cảm"
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 7,
                            GhiChu = "Sách học tập",
                            NgayChi = new DateTime(2026, 4, 18, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 260000m,
                            TenChiTieu = "Sách kỹ năng"
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 5,
                            GhiChu = "Hóa đơn sinh hoạt",
                            NgayChi = new DateTime(2026, 4, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 300000m,
                            TenChiTieu = "Tiền điện nước"
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 2,
                            GhiChu = "Trời mưa",
                            NgayChi = new DateTime(2026, 4, 22, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 90000m,
                            TenChiTieu = "Grab về nhà"
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 9,
                            GhiChu = "Gặp bạn cuối tuần",
                            NgayChi = new DateTime(2026, 4, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 150000m,
                            TenChiTieu = "Trà sữa"
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 10,
                            GhiChu = "Góp định kỳ",
                            NgayChi = new DateTime(2026, 4, 26, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 500000m,
                            TenChiTieu = "Đầu tư quỹ"
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 3,
                            GhiChu = "Phụ kiện làm việc",
                            NgayChi = new DateTime(2026, 4, 28, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 680000m,
                            TenChiTieu = "Mua thiết bị nhỏ"
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 5,
                            GhiChu = "Chi phí cố định tháng 5",
                            NgayChi = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 3600000m,
                            TenChiTieu = "Tiền thuê phòng"
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 1,
                            GhiChu = "Phở sáng",
                            NgayChi = new DateTime(2026, 5, 2, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 45000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 19,
                            DanhMucId = 2,
                            GhiChu = "Đi làm hằng ngày",
                            NgayChi = new DateTime(2026, 5, 4, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 130000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 20,
                            DanhMucId = 3,
                            GhiChu = "Đồ dùng cá nhân",
                            NgayChi = new DateTime(2026, 5, 6, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 220000m,
                            TenChiTieu = "Mua mỹ phẩm"
                        },
                        new
                        {
                            Id = 21,
                            DanhMucId = 5,
                            GhiChu = "Gia hạn công cụ",
                            NgayChi = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 320000m,
                            TenChiTieu = "Hóa đơn phần mềm"
                        },
                        new
                        {
                            Id = 22,
                            DanhMucId = 8,
                            GhiChu = "Du lịch ngắn ngày",
                            NgayChi = new DateTime(2026, 5, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 850000m,
                            TenChiTieu = "Đặt vé Đà Lạt"
                        },
                        new
                        {
                            Id = 23,
                            DanhMucId = 1,
                            GhiChu = "Cơm văn phòng",
                            NgayChi = new DateTime(2026, 5, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 24,
                            DanhMucId = 9,
                            GhiChu = "Cuối ngày",
                            NgayChi = new DateTime(2026, 5, 14, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 110000m,
                            TenChiTieu = "Cà phê gặp bạn"
                        },
                        new
                        {
                            Id = 25,
                            DanhMucId = 6,
                            GhiChu = "Kiểm tra định kỳ",
                            NgayChi = new DateTime(2026, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 280000m,
                            TenChiTieu = "Khám sức khỏe"
                        },
                        new
                        {
                            Id = 26,
                            DanhMucId = 1,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 5, 18, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 230000m,
                            TenChiTieu = "Ăn tối gia đình"
                        },
                        new
                        {
                            Id = 27,
                            DanhMucId = 5,
                            GhiChu = "Hóa đơn tháng 5",
                            NgayChi = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 350000m,
                            TenChiTieu = "Tiền điện nước"
                        },
                        new
                        {
                            Id = 28,
                            DanhMucId = 7,
                            GhiChu = "Nâng cấp kỹ năng",
                            NgayChi = new DateTime(2026, 5, 22, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 300000m,
                            TenChiTieu = "Khóa học online"
                        },
                        new
                        {
                            Id = 29,
                            DanhMucId = 4,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 5, 24, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 190000m,
                            TenChiTieu = "Xem phim"
                        },
                        new
                        {
                            Id = 30,
                            DanhMucId = 10,
                            GhiChu = "Góp định kỳ",
                            NgayChi = new DateTime(2026, 5, 26, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 600000m,
                            TenChiTieu = "Đầu tư quỹ"
                        },
                        new
                        {
                            Id = 31,
                            DanhMucId = 1,
                            GhiChu = "Ăn tối công việc",
                            NgayChi = new DateTime(2026, 5, 28, 17, 50, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 450000m,
                            TenChiTieu = "Tiếp khách"
                        },
                        new
                        {
                            Id = 32,
                            DanhMucId = 3,
                            GhiChu = "Chuẩn bị đi làm",
                            NgayChi = new DateTime(2026, 5, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 500000m,
                            TenChiTieu = "Mua balo"
                        },
                        new
                        {
                            Id = 33,
                            DanhMucId = 1,
                            GhiChu = "Bún bò",
                            NgayChi = new DateTime(2026, 6, 1, 7, 25, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 40000m,
                            TenChiTieu = "Ăn sáng đầu tháng"
                        },
                        new
                        {
                            Id = 34,
                            DanhMucId = 2,
                            GhiChu = "Chuẩn bị tuần mới",
                            NgayChi = new DateTime(2026, 6, 1, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 125000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 35,
                            DanhMucId = 5,
                            GhiChu = "Chi phí cố định tháng 6",
                            NgayChi = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 3600000m,
                            TenChiTieu = "Tiền thuê phòng"
                        },
                        new
                        {
                            Id = 36,
                            DanhMucId = 1,
                            GhiChu = "Cơm văn phòng",
                            NgayChi = new DateTime(2026, 6, 1, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 75000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 37,
                            DanhMucId = 5,
                            GhiChu = "Hóa đơn tháng 6",
                            NgayChi = new DateTime(2026, 6, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 250000m,
                            TenChiTieu = "Internet văn phòng"
                        },
                        new
                        {
                            Id = 38,
                            DanhMucId = 9,
                            GhiChu = "Làm việc cá nhân",
                            NgayChi = new DateTime(2026, 6, 1, 19, 40, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 95000m,
                            TenChiTieu = "Cà phê tối"
                        },
                        new
                        {
                            Id = 39,
                            DanhMucId = 1,
                            GhiChu = "Bánh cuốn",
                            NgayChi = new DateTime(2026, 6, 2, 7, 40, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 45000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 40,
                            DanhMucId = 1,
                            GhiChu = "Cơm phần",
                            NgayChi = new DateTime(2026, 6, 2, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa văn phòng"
                        },
                        new
                        {
                            Id = 41,
                            DanhMucId = 3,
                            GhiChu = "Dầu gội và sữa tắm",
                            NgayChi = new DateTime(2026, 6, 2, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 120000m,
                            TenChiTieu = "Mua đồ cá nhân"
                        },
                        new
                        {
                            Id = 42,
                            DanhMucId = 2,
                            GhiChu = "Tan làm muộn",
                            NgayChi = new DateTime(2026, 6, 2, 18, 25, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 85000m,
                            TenChiTieu = "Grab về nhà"
                        },
                        new
                        {
                            Id = 43,
                            DanhMucId = 4,
                            GhiChu = "Gia hạn dịch vụ tháng 6",
                            NgayChi = new DateTime(2026, 6, 2, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 59000m,
                            TenChiTieu = "Gói nghe nhạc"
                        },
                        new
                        {
                            Id = 44,
                            DanhMucId = 1,
                            GhiChu = "Bánh mì đầu ngày",
                            NgayChi = new DateTime(2026, 6, 3, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 35000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 45,
                            DanhMucId = 1,
                            GhiChu = "Cơm văn phòng",
                            NgayChi = new DateTime(2026, 6, 3, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 46,
                            DanhMucId = 2,
                            GhiChu = "Đi làm hằng ngày",
                            NgayChi = new DateTime(2026, 6, 4, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 120000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 47,
                            DanhMucId = 9,
                            GhiChu = "Giải lao buổi tối",
                            NgayChi = new DateTime(2026, 6, 4, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 50000m,
                            TenChiTieu = "Trà sữa"
                        },
                        new
                        {
                            Id = 48,
                            DanhMucId = 2,
                            GhiChu = "Phí gửi xe chung cư",
                            NgayChi = new DateTime(2026, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 180000m,
                            TenChiTieu = "Gửi xe tháng 6"
                        },
                        new
                        {
                            Id = 49,
                            DanhMucId = 1,
                            GhiChu = "Quán ăn gần nhà",
                            NgayChi = new DateTime(2026, 6, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 150000m,
                            TenChiTieu = "Ăn tối"
                        },
                        new
                        {
                            Id = 50,
                            DanhMucId = 1,
                            GhiChu = "Thực phẩm trong tuần",
                            NgayChi = new DateTime(2026, 6, 6, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 220000m,
                            TenChiTieu = "Đi chợ cuối tuần"
                        },
                        new
                        {
                            Id = 51,
                            DanhMucId = 4,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 6, 6, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 180000m,
                            TenChiTieu = "Xem phim"
                        },
                        new
                        {
                            Id = 52,
                            DanhMucId = 1,
                            GhiChu = "Cơm phần",
                            NgayChi = new DateTime(2026, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 65000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 53,
                            DanhMucId = 9,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 6, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 60000m,
                            TenChiTieu = "Cà phê gặp bạn"
                        },
                        new
                        {
                            Id = 54,
                            DanhMucId = 5,
                            GhiChu = "Gia hạn dung lượng",
                            NgayChi = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 49000m,
                            TenChiTieu = "Gói lưu trữ đám mây"
                        },
                        new
                        {
                            Id = 55,
                            DanhMucId = 2,
                            GhiChu = "Đi làm",
                            NgayChi = new DateTime(2026, 6, 8, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 110000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 56,
                            DanhMucId = 1,
                            GhiChu = "Phở sáng",
                            NgayChi = new DateTime(2026, 6, 9, 7, 40, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 40000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 57,
                            DanhMucId = 3,
                            GhiChu = "Đồ dùng nhà bếp",
                            NgayChi = new DateTime(2026, 6, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 320000m,
                            TenChiTieu = "Mua đồ gia dụng"
                        },
                        new
                        {
                            Id = 58,
                            DanhMucId = 5,
                            GhiChu = "Gói cước hằng tháng",
                            NgayChi = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 100000m,
                            TenChiTieu = "Nạp thẻ điện thoại"
                        },
                        new
                        {
                            Id = 59,
                            DanhMucId = 1,
                            GhiChu = "Cơm văn phòng",
                            NgayChi = new DateTime(2026, 6, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 60,
                            DanhMucId = 5,
                            GhiChu = "Gia hạn công cụ làm việc",
                            NgayChi = new DateTime(2026, 6, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 320000m,
                            TenChiTieu = "Hóa đơn phần mềm"
                        },
                        new
                        {
                            Id = 61,
                            DanhMucId = 1,
                            GhiChu = "Quây quần cuối tuần",
                            NgayChi = new DateTime(2026, 6, 11, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 240000m,
                            TenChiTieu = "Ăn tối gia đình"
                        },
                        new
                        {
                            Id = 62,
                            DanhMucId = 9,
                            GhiChu = "Buổi sáng",
                            NgayChi = new DateTime(2026, 6, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 95000m,
                            TenChiTieu = "Cà phê làm việc"
                        },
                        new
                        {
                            Id = 63,
                            DanhMucId = 6,
                            GhiChu = "Lịch khám theo tháng",
                            NgayChi = new DateTime(2026, 6, 12, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 300000m,
                            TenChiTieu = "Khám sức khỏe định kỳ"
                        },
                        new
                        {
                            Id = 64,
                            DanhMucId = 1,
                            GhiChu = "Cơm phần",
                            NgayChi = new DateTime(2026, 6, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 65,
                            DanhMucId = 2,
                            GhiChu = "Tan làm muộn",
                            NgayChi = new DateTime(2026, 6, 13, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 85000m,
                            TenChiTieu = "Grab về nhà"
                        },
                        new
                        {
                            Id = 66,
                            DanhMucId = 4,
                            GhiChu = "Giải trí cuối tuần",
                            NgayChi = new DateTime(2026, 6, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 95000m,
                            TenChiTieu = "Xem phim"
                        },
                        new
                        {
                            Id = 67,
                            DanhMucId = 1,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 6, 14, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 210000m,
                            TenChiTieu = "Ăn tối với bạn"
                        },
                        new
                        {
                            Id = 68,
                            DanhMucId = 7,
                            GhiChu = "Sách tham khảo",
                            NgayChi = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 150000m,
                            TenChiTieu = "Mua sách"
                        },
                        new
                        {
                            Id = 69,
                            DanhMucId = 7,
                            GhiChu = "Gia hạn khóa học kỹ năng",
                            NgayChi = new DateTime(2026, 6, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 300000m,
                            TenChiTieu = "Khóa học online tháng 6"
                        },
                        new
                        {
                            Id = 70,
                            DanhMucId = 1,
                            GhiChu = "Bánh mì",
                            NgayChi = new DateTime(2026, 6, 16, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 35000m,
                            TenChiTieu = "Ăn sáng"
                        },
                        new
                        {
                            Id = 71,
                            DanhMucId = 2,
                            GhiChu = "Đi làm",
                            NgayChi = new DateTime(2026, 6, 16, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 120000m,
                            TenChiTieu = "Đổ xăng"
                        },
                        new
                        {
                            Id = 72,
                            DanhMucId = 1,
                            GhiChu = "Cơm văn phòng",
                            NgayChi = new DateTime(2026, 6, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 70000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 73,
                            DanhMucId = 9,
                            GhiChu = "Giải lao",
                            NgayChi = new DateTime(2026, 6, 17, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 55000m,
                            TenChiTieu = "Trà sữa"
                        },
                        new
                        {
                            Id = 74,
                            DanhMucId = 1,
                            GhiChu = "Đồ ăn cho tuần giữa tháng",
                            NgayChi = new DateTime(2026, 6, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 450000m,
                            TenChiTieu = "Mua thực phẩm định kỳ"
                        },
                        new
                        {
                            Id = 75,
                            DanhMucId = 9,
                            GhiChu = "Làm việc cá nhân",
                            NgayChi = new DateTime(2026, 6, 18, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 90000m,
                            TenChiTieu = "Cà phê tối"
                        },
                        new
                        {
                            Id = 76,
                            DanhMucId = 3,
                            GhiChu = "Đồ dùng làm việc",
                            NgayChi = new DateTime(2026, 6, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 1,
                            SoTien = 180000m,
                            TenChiTieu = "Mua văn phòng phẩm"
                        },
                        new
                        {
                            Id = 77,
                            DanhMucId = 1,
                            GhiChu = "Cơm phần",
                            NgayChi = new DateTime(2026, 6, 19, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 65000m,
                            TenChiTieu = "Ăn trưa"
                        },
                        new
                        {
                            Id = 78,
                            DanhMucId = 5,
                            GhiChu = "Hóa đơn sinh hoạt",
                            NgayChi = new DateTime(2026, 6, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 360000m,
                            TenChiTieu = "Tiền điện nước tháng 6"
                        },
                        new
                        {
                            Id = 79,
                            DanhMucId = 3,
                            GhiChu = "Mua sắm cuối tuần",
                            NgayChi = new DateTime(2026, 6, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            SoTien = 280000m,
                            TenChiTieu = "Đi siêu thị"
                        },
                        new
                        {
                            Id = 80,
                            DanhMucId = 1,
                            GhiChu = "Cuối tuần",
                            NgayChi = new DateTime(2026, 6, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            SoTien = 130000m,
                            TenChiTieu = "Ăn tối"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieuTheoLich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("LanThucHienCuoi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayThucHien")
                        .HasColumnType("date");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenChiTieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChiTieuT__3214EC07DDC555D6");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("NgayThucHien")
                        .HasDatabaseName("IX_ChiTieuTheoLich_NgayThucHien");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("IX_ChiTieuTheoLich_NguoiDungId");

                    b.ToTable("ChiTieuTheoLich", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán tiền thuê phòng tháng 4",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 4, 5),
                            NgayThucHien = new DateOnly(2026, 4, 5),
                            NguoiDungId = 2,
                            SoTien = 3200000m,
                            TenChiTieu = "Tiền thuê phòng tháng 4"
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán Internet tháng 4",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 4, 10),
                            NgayThucHien = new DateOnly(2026, 4, 10),
                            NguoiDungId = 1,
                            SoTien = 250000m,
                            TenChiTieu = "Internet văn phòng tháng 4"
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán hóa đơn sinh hoạt tháng 4",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 4, 20),
                            NgayThucHien = new DateOnly(2026, 4, 20),
                            NguoiDungId = 3,
                            SoTien = 300000m,
                            TenChiTieu = "Tiền điện nước tháng 4"
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán tiền thuê phòng tháng 5",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 5, 1),
                            NgayThucHien = new DateOnly(2026, 5, 1),
                            NguoiDungId = 2,
                            SoTien = 3600000m,
                            TenChiTieu = "Tiền thuê phòng tháng 5"
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 5,
                            GhiChu = "Đã gia hạn công cụ làm việc",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 5, 8),
                            NgayThucHien = new DateOnly(2026, 5, 8),
                            NguoiDungId = 1,
                            SoTien = 320000m,
                            TenChiTieu = "Hóa đơn phần mềm tháng 5"
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 6,
                            GhiChu = "Đã hoàn thành lịch khám định kỳ",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 5, 16),
                            NgayThucHien = new DateOnly(2026, 5, 16),
                            NguoiDungId = 3,
                            SoTien = 280000m,
                            TenChiTieu = "Khám sức khỏe tháng 5"
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán hóa đơn sinh hoạt tháng 5",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 5, 20),
                            NgayThucHien = new DateOnly(2026, 5, 20),
                            NguoiDungId = 3,
                            SoTien = 350000m,
                            TenChiTieu = "Tiền điện nước tháng 5"
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán vào ngày đầu tháng",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 1),
                            NgayThucHien = new DateOnly(2026, 6, 1),
                            NguoiDungId = 2,
                            SoTien = 3600000m,
                            TenChiTieu = "Tiền thuê phòng tháng 6"
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 4,
                            GhiChu = "Đã gia hạn dịch vụ giải trí",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 2),
                            NgayThucHien = new DateOnly(2026, 6, 2),
                            NguoiDungId = 3,
                            SoTien = 59000m,
                            TenChiTieu = "Gói nghe nhạc tháng 6"
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 2,
                            GhiChu = "Đã thanh toán phí gửi xe chung cư",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 5),
                            NgayThucHien = new DateOnly(2026, 6, 5),
                            NguoiDungId = 2,
                            SoTien = 180000m,
                            TenChiTieu = "Gửi xe tháng 6"
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 5,
                            GhiChu = "Đã gia hạn dung lượng lưu trữ",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 8),
                            NgayThucHien = new DateOnly(2026, 6, 8),
                            NguoiDungId = 1,
                            SoTien = 49000m,
                            TenChiTieu = "Gói lưu trữ đám mây"
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 5,
                            GhiChu = "Đã nạp gói cước liên lạc hằng tháng",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 10),
                            NgayThucHien = new DateOnly(2026, 6, 10),
                            NguoiDungId = 2,
                            SoTien = 100000m,
                            TenChiTieu = "Nạp thẻ điện thoại"
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 6,
                            GhiChu = "Đã hoàn thành lịch khám theo tháng",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 12),
                            NgayThucHien = new DateOnly(2026, 6, 12),
                            NguoiDungId = 3,
                            SoTien = 300000m,
                            TenChiTieu = "Khám sức khỏe định kỳ"
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 7,
                            GhiChu = "Đã gia hạn khóa học kỹ năng",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 15),
                            NgayThucHien = new DateOnly(2026, 6, 15),
                            NguoiDungId = 2,
                            SoTien = 300000m,
                            TenChiTieu = "Khóa học online tháng 6"
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 1,
                            GhiChu = "Đã mua đồ ăn cho tuần giữa tháng",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 18),
                            NgayThucHien = new DateOnly(2026, 6, 18),
                            NguoiDungId = 3,
                            SoTien = 450000m,
                            TenChiTieu = "Mua thực phẩm định kỳ"
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 5,
                            GhiChu = "Đã thanh toán hóa đơn sinh hoạt tháng 6",
                            HoatDong = false,
                            LanThucHienCuoi = new DateOnly(2026, 6, 20),
                            NgayThucHien = new DateOnly(2026, 6, 20),
                            NguoiDungId = 3,
                            SoTien = 360000m,
                            TenChiTieu = "Tiền điện nước tháng 6"
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 9,
                            GhiChu = "Dự kiến gặp bạn làm việc cuối tuần",
                            HoatDong = true,
                            LanThucHienCuoi = new DateOnly(2026, 5, 14),
                            NgayThucHien = new DateOnly(2026, 6, 23),
                            NguoiDungId = 2,
                            SoTien = 120000m,
                            TenChiTieu = "Cà phê làm việc định kỳ"
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 10,
                            GhiChu = "Góp quỹ định kỳ cuối tháng",
                            HoatDong = true,
                            LanThucHienCuoi = new DateOnly(2026, 5, 26),
                            NgayThucHien = new DateOnly(2026, 6, 26),
                            NguoiDungId = 2,
                            SoTien = 600000m,
                            TenChiTieu = "Đầu tư quỹ tháng 6"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauSac")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TuDongPhanLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC07C2C35FB3");

                    b.HasIndex("TenDanhMuc")
                        .HasDatabaseName("IX_DanhMuc_TenDanhMuc");

                    b.ToTable("DanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MauSac = "#FF6384",
                            TenDanhMuc = "Ăn uống",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 2,
                            MauSac = "#36A2EB",
                            TenDanhMuc = "Di chuyển",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 3,
                            MauSac = "#FFCE56",
                            TenDanhMuc = "Mua sắm",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 4,
                            MauSac = "#4BC0C0",
                            TenDanhMuc = "Giải trí",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 5,
                            MauSac = "#9966FF",
                            TenDanhMuc = "Hóa đơn",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 6,
                            MauSac = "#FF9F40",
                            TenDanhMuc = "Sức khỏe",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 7,
                            MauSac = "#FFCD56",
                            TenDanhMuc = "Giáo dục",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 8,
                            MauSac = "#C9CBCF",
                            TenDanhMuc = "Du lịch",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 9,
                            MauSac = "#8E5EA2",
                            TenDanhMuc = "Cà phê",
                            TuDongPhanLoai = true
                        },
                        new
                        {
                            Id = 10,
                            MauSac = "#3D9970",
                            TenDanhMuc = "Đầu tư",
                            TuDongPhanLoai = true
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.GioiHanChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GioiHanC__3214EC078D4B0F17");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("IX_GioiHanChiTieu_NguoiDungId");

                    b.HasIndex("Thang", "Nam")
                        .HasDatabaseName("IX_GioiHanChiTieu_Thang_Nam");

                    b.HasIndex("NguoiDungId", "Thang", "Nam")
                        .IsUnique()
                        .HasDatabaseName("IX_GioiHanChiTieu_NguoiDung_Thang_Nam");

                    b.HasIndex(new[] { "Thang", "Nam" }, "IX_GioiHanChiTieu_Thang_Nam");

                    b.ToTable("GioiHanChiTieu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nam = 2026,
                            NguoiDungId = 1,
                            SoTienToiDa = 2500000m,
                            Thang = 4
                        },
                        new
                        {
                            Id = 2,
                            Nam = 2026,
                            NguoiDungId = 2,
                            SoTienToiDa = 6500000m,
                            Thang = 4
                        },
                        new
                        {
                            Id = 3,
                            Nam = 2026,
                            NguoiDungId = 3,
                            SoTienToiDa = 3500000m,
                            Thang = 4
                        },
                        new
                        {
                            Id = 4,
                            Nam = 2026,
                            NguoiDungId = 1,
                            SoTienToiDa = 2500000m,
                            Thang = 5
                        },
                        new
                        {
                            Id = 5,
                            Nam = 2026,
                            NguoiDungId = 2,
                            SoTienToiDa = 7500000m,
                            Thang = 5
                        },
                        new
                        {
                            Id = 6,
                            Nam = 2026,
                            NguoiDungId = 3,
                            SoTienToiDa = 4000000m,
                            Thang = 5
                        },
                        new
                        {
                            Id = 7,
                            Nam = 2026,
                            NguoiDungId = 1,
                            SoTienToiDa = 3000000m,
                            Thang = 6
                        },
                        new
                        {
                            Id = 8,
                            Nam = 2026,
                            NguoiDungId = 2,
                            SoTienToiDa = 8500000m,
                            Thang = 6
                        },
                        new
                        {
                            Id = 9,
                            Nam = 2026,
                            NguoiDungId = 3,
                            SoTienToiDa = 4500000m,
                            Thang = 6
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.LichSuNhanNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiNhanNhac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__LichSuNh__3214EC07A3A7D1EB");

                    b.HasIndex("NgayGui")
                        .HasDatabaseName("IX_LichSuNhanNhac_NgayGui");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("IX_LichSuNhanNhac_NguoiDungId");

                    b.HasIndex(new[] { "NgayGui" }, "IX_LichSuNhanNhac_NgayGui");

                    b.ToTable("LichSuNhanNhac", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoaiNhanNhac = "HangNgay",
                            NgayGui = new DateTime(2026, 4, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Đừng quên ghi lại chi tiêu hôm nay.",
                            TieuDe = "Nhắc nhập chi tiêu",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            LoaiNhanNhac = "HoaDon",
                            NgayGui = new DateTime(2026, 4, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Bạn có hóa đơn điện nước cần thanh toán.",
                            TieuDe = "Nhắc thanh toán hóa đơn",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            LoaiNhanNhac = "HangThang",
                            NgayGui = new DateTime(2026, 5, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Kiểm tra lại chi tiêu tháng 5 trước khi sang tháng mới.",
                            TieuDe = "Tổng kết tháng 5",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            LoaiNhanNhac = "HangNgay",
                            NgayGui = new DateTime(2026, 6, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Ngày 02/06/2026 đã có thêm một số khoản chi tiêu cần kiểm tra.",
                            TieuDe = "Nhắc ghi chi tiêu đầu tháng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            LoaiNhanNhac = "ChiTieuTheoLich",
                            NgayGui = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Bạn có lịch khám sức khỏe vào ngày 12/06/2026.",
                            TieuDe = "Nhắc khám sức khỏe định kỳ",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 6,
                            LoaiNhanNhac = "ChiTieuTheoLich",
                            NgayGui = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Đến hạn gia hạn khóa học online ngày 15/06/2026.",
                            TieuDe = "Nhắc gia hạn khóa học",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 7,
                            LoaiNhanNhac = "HoaDon",
                            NgayGui = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Hóa đơn điện nước tháng 6 đến hạn ngày 20/06/2026.",
                            TieuDe = "Nhắc thanh toán hóa đơn",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly?>("GioNhanNhac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(18, 0, 0));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LoaiTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool?>("NhanEmailNhacNho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TanSuatNhanNhac")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("HangTuan");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3214EC07CF5C7E6E");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ__NguoiDun__A9D10534A0F8E828");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534A0F8E828")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://ui-avatars.com/api/?name=admin&background=00112C&color=fff",
                            Email = "admin@qlct.com",
                            GioNhanNhac = new TimeOnly(8, 0, 0),
                            HoTen = "admin",
                            LoaiTaiKhoan = 1,
                            MatKhau = "ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f",
                            NgayDangKy = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NhanEmailNhacNho = true,
                            TanSuatNhanNhac = "HangNgay"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://ui-avatars.com/api/?name=user1&background=36A2EB&color=fff",
                            Email = "user1@qlct.com",
                            GioNhanNhac = new TimeOnly(20, 0, 0),
                            HoTen = "user1",
                            LoaiTaiKhoan = 0,
                            MatKhau = "ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f",
                            NgayDangKy = new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            NhanEmailNhacNho = true,
                            TanSuatNhanNhac = "HangNgay"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://ui-avatars.com/api/?name=user2&background=FF6384&color=fff",
                            Email = "user2@qlct.com",
                            GioNhanNhac = new TimeOnly(19, 30, 0),
                            HoTen = "user2",
                            LoaiTaiKhoan = 0,
                            MatKhau = "ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f",
                            NgayDangKy = new DateTime(2026, 2, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            NhanEmailNhacNho = true,
                            TanSuatNhanNhac = "HangTuan"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Otp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaOtp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaOTP");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK__OTP__3214EC0766DF5851");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_OTP_Email");

                    b.HasIndex("MaOtp")
                        .HasDatabaseName("IX_OTP_MaOTP");

                    b.ToTable("OTP", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@qlct.com",
                            MaOtp = "102938",
                            ThoiGianTao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 2,
                            Email = "user1@qlct.com",
                            MaOtp = "564738",
                            ThoiGianTao = new DateTime(2026, 6, 1, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "user2@qlct.com",
                            MaOtp = "918273",
                            ThoiGianTao = new DateTime(2026, 6, 2, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ThongBao__3214EC07F56E0324");

                    b.HasIndex("NgayGui")
                        .HasDatabaseName("IX_ThongBao_NgayGui");

                    b.HasIndex("NguoiDungId")
                        .HasDatabaseName("IX_ThongBao_NguoiDungId");

                    b.HasIndex(new[] { "NguoiDungId" }, "IX_ThongBao_NguoiDungId");

                    b.ToTable("ThongBao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaDoc = true,
                            NgayGui = new DateTime(2026, 4, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Bạn đã sử dụng khoảng 70% hạn mức tháng 4/2026."
                        },
                        new
                        {
                            Id = 2,
                            DaDoc = true,
                            NgayGui = new DateTime(2026, 4, 20, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Hóa đơn điện nước tháng 4 đã được ghi nhận."
                        },
                        new
                        {
                            Id = 3,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 5, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Bạn có lịch đầu tư quỹ vào ngày 26/05/2026."
                        },
                        new
                        {
                            Id = 4,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 5, 30, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Tổng chi tiêu tháng 5 vẫn nằm trong hạn mức."
                        },
                        new
                        {
                            Id = 5,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 6, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Đã ghi nhận chi tiêu đến ngày 02/06/2026. Hạn mức tháng 6 vẫn còn an toàn."
                        },
                        new
                        {
                            Id = 6,
                            DaDoc = true,
                            NgayGui = new DateTime(2026, 6, 2, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Bạn có 2 khoản chi tiêu theo lịch sắp tới trong tháng 6/2026."
                        },
                        new
                        {
                            Id = 7,
                            DaDoc = true,
                            NgayGui = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Khám sức khỏe định kỳ ngày 12/06/2026 đã được ghi nhận."
                        },
                        new
                        {
                            Id = 8,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Bạn đã sử dụng khoảng 65% hạn mức tháng 6/2026."
                        },
                        new
                        {
                            Id = 9,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3,
                            NoiDung = "Hóa đơn điện nước tháng 6 đã được thanh toán ngày 20/06/2026."
                        },
                        new
                        {
                            Id = 10,
                            DaDoc = false,
                            NgayGui = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 2,
                            NoiDung = "Sắp tới hạn đầu tư quỹ định kỳ ngày 26/06/2026."
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.TuKhoaDanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("TuKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TuKhoaDa__3214EC077923D733");

                    b.HasIndex("DanhMucId")
                        .HasDatabaseName("IX_TuKhoaDanhMuc_DanhMucId");

                    b.HasIndex("TuKhoa")
                        .HasDatabaseName("IX_TuKhoaDanhMuc_TuKhoa");

                    b.HasIndex(new[] { "TuKhoa" }, "IX_TuKhoaDanhMuc_TuKhoa");

                    b.ToTable("TuKhoaDanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 1,
                            TuKhoa = "ăn"
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 1,
                            TuKhoa = "cơm"
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 1,
                            TuKhoa = "bún"
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 2,
                            TuKhoa = "xăng"
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 2,
                            TuKhoa = "grab"
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 2,
                            TuKhoa = "xe"
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 3,
                            TuKhoa = "mua"
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 3,
                            TuKhoa = "áo"
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 3,
                            TuKhoa = "balo"
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 4,
                            TuKhoa = "phim"
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 4,
                            TuKhoa = "giải trí"
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 5,
                            TuKhoa = "hóa đơn"
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 5,
                            TuKhoa = "tiền nhà"
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 5,
                            TuKhoa = "internet"
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 6,
                            TuKhoa = "thuốc"
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 6,
                            TuKhoa = "khám"
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 7,
                            TuKhoa = "học"
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 7,
                            TuKhoa = "sách"
                        },
                        new
                        {
                            Id = 19,
                            DanhMucId = 8,
                            TuKhoa = "du lịch"
                        },
                        new
                        {
                            Id = 20,
                            DanhMucId = 8,
                            TuKhoa = "vé"
                        },
                        new
                        {
                            Id = 21,
                            DanhMucId = 9,
                            TuKhoa = "cà phê"
                        },
                        new
                        {
                            Id = 22,
                            DanhMucId = 9,
                            TuKhoa = "trà sữa"
                        },
                        new
                        {
                            Id = 23,
                            DanhMucId = 10,
                            TuKhoa = "đầu tư"
                        },
                        new
                        {
                            Id = 24,
                            DanhMucId = 10,
                            TuKhoa = "quỹ"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.VwThongKeChiTieu", b =>
                {
                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_ThongKeChiTieu", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieu", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany("ChiTieus")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieu__DanhMuc__440B1D61");

                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChiTieus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieu__NguoiDu__4316F928");

                    b.Navigation("DanhMuc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieuTheoLich", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany("ChiTieuTheoLiches")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieuTh__DanhM__71D1E811");

                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChiTieuTheoLiches")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieuTh__Nguoi__70DDC3D8");

                    b.Navigation("DanhMuc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.GioiHanChiTieu", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioiHanChiTieus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioiHanCh__Nguoi__46E78A0C");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.LichSuNhanNhac", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuNhanNhacs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LichSuNha__Nguoi__571DF1D5");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ThongBao__NguoiD__4BAC3F29");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.TuKhoaDanhMuc", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany("TuKhoaDanhMucs")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TuKhoaDan__DanhM__52593CB8");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.DanhMuc", b =>
                {
                    b.Navigation("ChiTieuTheoLiches");

                    b.Navigation("ChiTieus");

                    b.Navigation("TuKhoaDanhMucs");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Navigation("ChiTieuTheoLiches");

                    b.Navigation("ChiTieus");

                    b.Navigation("GioiHanChiTieus");

                    b.Navigation("LichSuNhanNhacs");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
